version: "3.7"

services:
  pg:
    image: bitnami/postgresql
    container_name: crux-pg
    environment:
      POSTGRES_USER: cruxtest
      POSTGRES_PASSWORD: cruxtest
      POSTGRES_DB: cruxtest
    ports:
      - "5432:5432"
